version: '3.7'
services:
  memo-nginx:
    container_name: memo-nginx
    image: nginx
    restart: always
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - memosocket:/tmp
    networks:
      - memonet
    depends_on:
      - memo-web
    ports:
      - 80:80

  memo-web:
    container_name: memo-web
    image: memo-web
    build: .
    networks:
      - memonet
    # ports:
    #   - 8080:8080
    # depends_on:
    #   - memo-db
    volumes:
      - ./:/var/www/project
      - memosocket:/tmp
    restart: always
    environment:
      - FLASK_APP=project
      - FLASK_ENV=${FLASK_ENV:-development}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    command: ['sh', './etc/docker-entrypoint.sh']

networks:
  memonet:

volumes:
  memosocket: