version: '3.7'
services:
  memo-web:
    container_name: memo-web
    image: memo-web
    build: .
    networks:
      - memonet
    ports:
      - 8080:8080
    depends_on:
      - memo-db
    volumes:
      - ./:/var/www/project
    restart: always
    environment:
      - FLASK_APP=project
      - FLASK_ENV=${FLASK_ENV:-development}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    command: ['sh', './etc/docker-entrypoint.sh']
    
  memo-db:
    container_name: memo-db
    image: mysql:5.7
    networks:
      - memonet
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
      - 3306:3306
    volumes:
      - memovolume:/var/lib/mysql
    restart: always

networks:
  memonet:

volumes:
  memovolume: