"""Added Column to User Model

Revision ID: 15917fea7ab2
Revises: f46b46ffe0cb
Create Date: 2022-04-07 20:47:34.567598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15917fea7ab2'
down_revision = 'f46b46ffe0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
