"""Added Relationship

Revision ID: 430b59310c93
Revises: 7db03bcac99f
Create Date: 2022-04-15 12:00:09.558416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430b59310c93'
down_revision = '7db03bcac99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memos_labels',
    sa.Column('memo_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['memo_id'], ['memo.id'], ),
    sa.PrimaryKeyConstraint('memo_id', 'label_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memos_labels')
    # ### end Alembic commands ###
