"""Added new field to memo model

Revision ID: b196fd7932f7
Revises: 5623165350d3
Create Date: 2022-04-12 17:57:37.993096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b196fd7932f7'
down_revision = '5623165350d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memo', sa.Column('linked_image', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memo', 'linked_image')
    # ### end Alembic commands ###
